# Generated by Django 3.0.5 on 2020-04-20 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='سیم به کابل', help_text='عنوان', max_length=100)),
                ('contract_type', models.CharField(default='کلید در دست', help_text='نوع قرارداد', max_length=100)),
                ('place_of_make_contract', models.CharField(default='ستاد شرکت', help_text='محل عقد قرارداد', max_length=100)),
                ('contractor', models.CharField(help_text='پیمانکار', max_length=100)),
                ('contract_id', models.CharField(help_text='شماره قرارداد', max_length=50)),
                ('contract_start_date', models.DateField(help_text='تاریخ قرارداد')),
                ('contract_length', models.IntegerField(help_text='مدت قرارداد')),
                ('contract_cost', models.FloatField(help_text='مبلغ قرارداد (میلیون ریال)')),
                ('place_of_project', models.CharField(help_text='محل اجرای پروژه', max_length=100)),
                ('contract_volume', models.IntegerField(help_text='حجم قرارداد (کیلومتر)')),
                ('physical_progress', models.FloatField(default=0.0, help_text='درصد پیشرفت فیزیکی')),
                ('financial_progress', models.FloatField(default=0.0, help_text='درصد پیشرفت مالی')),
                ('recycled_conductor', models.FloatField(default=0.0, help_text='مقدار سیم برکناری')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
