# Generated by Django 3.0.5 on 2020-04-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contract_length',
            field=models.IntegerField(help_text='مدت قرارداد (ماه)'),
        ),
    ]
