# Generated by Django 3.0.5 on 2020-04-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200420_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contract_cost',
            field=models.FloatField(help_text='مبلغ قرارداد - میلیون ریال'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contract_length',
            field=models.IntegerField(help_text='مدت قرارداد - ماه'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contract_volume',
            field=models.IntegerField(help_text='حجم قرارداد - کیلومتر'),
        ),
    ]
