# Generated by Django 3.0.5 on 2020-04-22 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200420_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='گزارش روزانه', help_text='عنوان', max_length=100)),
                ('report_type', models.CharField(choices=[('tir', 'تیر'), ('conductor', 'هادی'), ('trans', 'ترانس')], help_text='نوع گزارش', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('physical_progress', models.FloatField(help_text='درصد پیشرفت', max_length=6)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
    ]
